# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 361)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(524, 318))
        self.centralwidget.setMaximumSize(QtCore.QSize(568, 402))
        self.centralwidget.setObjectName("centralwidget")
        self.projectList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.projectList.setGeometry(QtCore.QRect(20, 50, 281, 241))
        self.projectList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.projectList.setAutoScroll(True)
        self.projectList.setObjectName("projectList")
        self.chooseBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.chooseBox.setGeometry(QtCore.QRect(20, 10, 121, 22))
        self.chooseBox.setObjectName("chooseBox")
        self.chooseBox.addItem("")
        self.editProgram = QtWidgets.QPushButton(parent=self.centralwidget)
        self.editProgram.setGeometry(QtCore.QRect(150, 10, 91, 24))
        self.editProgram.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.editProgram.setObjectName("editProgram")
        self.addProject = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addProject.setGeometry(QtCore.QRect(350, 80, 75, 24))
        self.addProject.setObjectName("addProject")
        self.deleteProject = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteProject.setGeometry(QtCore.QRect(350, 110, 81, 24))
        self.deleteProject.setObjectName("deleteProject")
        self.exportProject = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exportProject.setGeometry(QtCore.QRect(350, 140, 81, 24))
        self.exportProject.setObjectName("exportProject")
        self.openProject = QtWidgets.QPushButton(parent=self.centralwidget)
        self.openProject.setGeometry(QtCore.QRect(350, 170, 111, 24))
        self.openProject.setObjectName("openProject")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseBox.setItemText(0, _translate("MainWindow", "Choose Program"))
        self.editProgram.setText(_translate("MainWindow", "Edit Programs"))
        self.addProject.setText(_translate("MainWindow", "Add Project"))
        self.deleteProject.setText(_translate("MainWindow", "Delete Project"))
        self.exportProject.setText(_translate("MainWindow", "Export Project"))
        self.openProject.setText(_translate("MainWindow", "Open Project Folder"))
